'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強類型資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("svchost.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強類型資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類似 日a
        '''曰a
        '''昌aa
        '''昍aa
        '''晶aaa
        '''暘aamh
        '''晹aaph
        '''暍aapv
        '''曝aate
        '''暻aayf
        '''明ab
        '''暝abac
        '''曖abbe
        '''盟abbt
        '''鷳abhaf
        '''猒abik
        '''曌abjcm
        '''暉abjj
        '''暈abjj
        '''暖abme
        '''勗abms
        '''暩abof
        '''冒abu
        '''晛abuu
        '''暡acim
        '''晜acnh
        '''昐acsh
        '''杲ad
        '''鷴adhaf
        '''晰adhl
        '''暐admq
        '''暕adwf
        '''鄤aenl
        '''炅af
        '''炚af
        '''曭afbf
        '''暽afdq
        '''晱aff
        '''影afhhh
        '''顥afmbc
        '''顯afmbc
        '''晃afmu
        '''歞afno
        '''曀agbt
        '''時agdi
        '''曉aggu
        '''晌ahbr
        '''晑ahbr
        '''眉ahbu
        '''昄ahe
        '''曛ahgf
        '''昴ahhl
        '''剔ahln
        '''昕ahml
        '''暀ahog
        '''暰ahoo
        '''晷ahor
        '''星ahqm
        '''昳ahqo
        '''昨ahs
        '''昈ahs
        '''曒ahsk
        '''昇aht
        '''昂ahvl
        '''晲ahxu
        '''晙aice
        '''晟aihs
        '''晡aijb
        '''既aimvu
        '''昹aine
        '''即aisl
        '''曠aitc
        '''早aj
        '''暔ajbj
        '''昧ajd
        '''暷ajii
        '''暑 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property b5xp_map() As String
            Get
                Return ResourceManager.GetString("b5xp_map", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 日a
        '''曰a
        '''昌aa
        '''昍aa
        '''晶aaa
        '''晿aaa
        '''曑aaah
        '''曡aaam
        '''曐aaam
        '''曟aaav
        '''覸aabuu
        '''焸aaf
        '''鷼aahaf
        '''暒aahm
        '''暥aajv
        '''暘aamh
        '''晘aamj
        '''晹aaph
        '''暍aapv
        '''曝aate
        '''暻aayf
        '''明ab
        '''冐ab
        '''暝abac
        '''曖abbe
        '''暧abbe
        '''盟abbt
        '''覵abbuu
        '''焽abf
        '''晭abgr
        '''鷳abhaf
        '''猒abik
        '''曌abjcm
        '''暈abjj
        '''暉abjj
        '''晕abkq
        '''晖abkq
        '''暖abme
        '''琞abmgi
        '''晍abmr
        '''勗abms
        '''暩abof
        '''暚abou
        '''昷abt
        '''冒abu
        '''晛abuu
        '''昖aci
        '''暡acim
        '''顕acmbc
        '''晜acnh
        '''昐acsh
        '''杲ad
        '''晽add
        '''鷴adhaf
        '''晰adhl
        '''时adi
        '''昩adj
        '''暐admq
        '''暕adwf
        '''鄤aenl
        '''炅af
        '''炚af
        '''曭afbf
        '''暽afdq
        '''晱aff
        '''影afhhh
        '''顯afmbc
        '''顥afmbc
        '''颢afmbo
        '''晃afmu
        '''晄afmu
        '''歞afno
        '''圼ag
        '''曀agbt
        '''時agdi
        '''晆agg
        '''曉a [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property cj5_map() As String
            Get
                Return ResourceManager.GetString("cj5_map", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property img() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("img", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property lui() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("lui", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 0,！：；。，、—？…
        '''09,‘】’（…）〔【〕︼」︻《÷》｛「｝︶︸︺〈＆〉︵︷︹﹙％﹚﹛＄﹜﹝￥﹞﹂』﹄﹁『﹃︾℃﹀＃＊※︽℉︿ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩ〡〢〣〤〥〦〧〨〩十卄卅．‧︰‥﹐﹑﹒·﹔﹕﹖﹗｜–︱︳︴﹏“”〝〞‵′ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ§〃○●△▲◎☆★◇◆□■▽▼㊣℅¯＿﹉﹊﹍﹎﹋﹌﹟﹠﹡＋－×±√＜＞＝≦≧≠∞≒≡﹢﹣﹤﹥﹦～∩∪⊥∠∟⊿㏒㏑∫∮∵∴♀♂⊕⊙↑↓←→↖↗↙↘∥∣∕﹨〒￠￡＠﹩﹪﹫㏕㎜㎝㎞㏎㎡㎎㎏㏄°▁▂▃▄▅▆▇█▏▎▍▌▋▊▉┼┴┬┤├▔─│▕┌┐└┘╭╮╰╯◢◣◥◤╱╲╳ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩαβγδεζηθικλμνξοπρστυφχψωㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦㄧㄨㄩ˙ˉˊˇˋ
        '''110,華萬夢若著花落英苦幕蘭舊草莫藝葉薦藍藏蓋藥蔡蘇蒼茶芳菜莊蕭藉蓮慕葛藤薩芬菩荒莉蒙艾薪菲蔣萊茫薄惹莎荷芒茂苗蓉暮茲芭萍曹蘋菁墓董蕩芝苑募薰蒂范菊蘊薇蓄葬蓬蕾葡蒸菌蘿萄蕃薯薛芷繭芙芋茵苛荳蕉芽蔚蔔蔥葵蔽蘆茹菱蔭芸菸蒐萱葦孽萃苟蕙芹茅蕊莽蔓茍萎 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property mapped_char() As String
            Get
                Return ResourceManager.GetString("mapped_char", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 0 菱令苓楞零齡玲呤稜軨羚陵〇鈴伶棱凌爧聆靈檸
        '''1 有壹一
        '''2 廿也吔誼易二議食肄異施貳義咦
        '''3 衫叁三叄
        '''4 肆四
        '''5 嗯晤誤
        '''6 麓轆碌睩鹿綠六錄淥陸氯戮祿
        '''7 柒𨳍柒漆七
        '''8 捌八
        '''9 赳笱韭苟韮糾久狗玖九枸
        '''耀 燿
        '''涉 葉攝懾
        '''伊 姨E意衤咿𪘲依兒咦醫衣
        '''唎 呢嚟哩喱力哩厘理璃籬痢匿篱喱
        '''預 諭豫着籲喻馭禦銣寓愉癒御譽裕遇瘉愈隅
        '''亟 極擊棘激戟
        '''洞 動幢慟桐戙峒棟恫胴
        '''猢 葫和糊鬍蝴湖瑚弧狐衚烏壺胡
        '''礦 擴曠
        '''鶩 霧暮帽戊摹務冒墓募慕
        '''河 可嗬何荷何合
        '''吸 汲岌級給扱𢲩笈
        '''娼 倡猖䱽鯧窗槍鎗鏘昌
        '''談 鐔燂痰潭譚曇
        '''反 販犯𠆩翻返瓣
        '''牌 排
        '''姑 古菇鴣苦軲咕轂孤沽辜菰
        '''織 職則癪漬嘖稷唧即蹟績積跡
        '''遠 阮軟薳
        '''知 資姿茲芝螆髭置氏之蜘子咨諮肢紙吱脂支G孜の孳枝滋智質置緻漬痣至誌摯致志
        '''除 徐捶隋搥蜍鎚錘俎廚槌隨𡃴
        '''緩 垣援媛瘓奐煥換玩喚
        '''彪 鏢錶表標熛鑣票飆
        '''歲 説帥税說嵗稅碎
        '''鯽 則鰂仄側
        '''廿 2也吔偌夜
        '''覆 馥蝠輻復福腹幅複
        '''瀋 嬸糝沈審
        '''儡 屢磊壘裏侶旅鋁女櫚呂蕾裡
        '''崩 𧌇繃蹦烹
        '''挭 浭逕
        '''芬 吩薰昏葷分婚勳燻番醺熏氛紛勛
        '''冶 嘢野夜若惹
        '''骼 鉻駱樂諾絡酪貉洛落𠺝革格隔胳膈鎘
        '''鍍 導 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property mapped_homograph() As String
            Get
                Return ResourceManager.GetString("mapped_homograph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 我你這好到資就個能的
        '''一個樣次些種齊般定起
        '''丁丑香美興文
        '''七律十月年公七倍大零
        '''乃至是
        '''九十五三九月方百倍州
        '''了不解得了事斷然結五
        '''二線流戰日號期萬百回
        '''人家員民生們類物士才
        '''入境學門侵選法會場睡
        '''八百十九月年字倍戒方
        '''刀子劍鋒槍法鞘直切闊
        '''力氣量不學度圖爭行竭
        '''匕首戲
        '''十分份五年二三月足倍
        '''又是有要在來如會叫吃
        '''三十月年個峽角分份倍
        '''下去子來面午降遊雨班
        '''丈夫人量天他個
        '''上海來面帝去課市遊級
        '''丫環頭鬟兒巴杈
        '''丸兒子藥
        '''凡爾人是事他響脫此
        '''久違久遠經而別仰留已
        '''也是不許就要有會能得
        '''乞丐討求食恕
        '''亡命國羊率事
        '''兀自
        '''刃之
        '''勺子
        '''千里金古萬秋年山百元
        '''口袋中氣水號味服頭紅
        '''土壤人地豆著氣洋法星
        '''士卒學氣人兵比頓大後
        '''夕陽改照
        '''大家概學陸多量約雨師
        '''女兒子性孩人友生郎士
        '''子弟女彈來孫不大打里
        '''孑立然
        '''小姐時小孩說心鎮型組
        '''山上穀東西坡水洞川林
        '''川流江萊省市貝資
        '''工作資業人程具藝廠商
        '''己任有見身道救為
        '''已經往有婚故見知辦過
        '''巳時
        '''弓箭蛇
        '''才是有子能華智行會幹
        '''不可能過知會是斷如但
        '''中央國共心文華間日毒
        '''丹麥陽田藥青妙 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property related_char() As String
            Get
                Return ResourceManager.GetString("related_char", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property VBHotkeyLib() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("VBHotkeyLib", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
