'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強類型資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("svchost.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強類型資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類似 日a
        '''曰a
        '''昌aa
        '''昍aa
        '''晶aaa
        '''暘aamh
        '''晹aaph
        '''暍aapv
        '''曝aate
        '''暻aayf
        '''明ab
        '''暝abac
        '''曖abbe
        '''盟abbt
        '''鷳abhaf
        '''猒abik
        '''曌abjcm
        '''暉abjj
        '''暈abjj
        '''暖abme
        '''勗abms
        '''暩abof
        '''冒abu
        '''晛abuu
        '''暡acim
        '''晜acnh
        '''昐acsh
        '''杲ad
        '''鷴adhaf
        '''晰adhl
        '''暐admq
        '''暕adwf
        '''鄤aenl
        '''炅af
        '''炚af
        '''曭afbf
        '''暽afdq
        '''晱aff
        '''影afhhh
        '''顥afmbc
        '''顯afmbc
        '''晃afmu
        '''歞afno
        '''曀agbt
        '''時agdi
        '''曉aggu
        '''晌ahbr
        '''晑ahbr
        '''眉ahbu
        '''昄ahe
        '''曛ahgf
        '''昴ahhl
        '''剔ahln
        '''昕ahml
        '''暀ahog
        '''暰ahoo
        '''晷ahor
        '''星ahqm
        '''昳ahqo
        '''昨ahs
        '''昈ahs
        '''曒ahsk
        '''昇aht
        '''昂ahvl
        '''晲ahxu
        '''晙aice
        '''晟aihs
        '''晡aijb
        '''既aimvu
        '''昹aine
        '''即aisl
        '''曠aitc
        '''早aj
        '''暔ajbj
        '''昧ajd
        '''暷ajii
        '''暑 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property b5xp_map() As String
            Get
                Return ResourceManager.GetString("b5xp_map", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 9EB3,4E04
        '''9EB2,4E1A
        '''9DD6,4E1C
        '''994F,4E21
        '''89CE,4E24
        '''9C71,20021
        '''8946,4E3D
        '''9375,2003E
        '''9376,20046
        '''9548,2004E
        '''8BC0,4E28
        '''9FC4,4E2A
        '''8BD4,4E2C
        '''8C72,4E2F
        '''8EC6,20068
        '''C6BF,4E36
        '''8BF9,4E37
        '''FAE5,4E49
        '''C6C0,4E3F
        '''8BC5,20086
        '''8BFA,20087
        '''C87C,2008A
        '''9AB4,20094
        '''C87B,4E5A
        '''8BC6,4E5B
        '''884E,200CA
        '''884B,200CB
        '''C87A,200CC
        '''8848,200CD
        '''8847,200D1
        '''9C57,4E6A
        '''9AFB,4E78
        '''A0F6,200EE
        '''89D0,4E80
        '''89CF,4E81
        '''8AA8,221A1
        '''C6C1,4E85
        '''8845,2010C
        '''8853,2010E
        '''89D1,4E87
        '''FCAD,20118
        '''C8D6,2E80
        '''C8D7,2E84
        '''C8D8,2E86
        '''C8D9,2E87 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property big5unicode_map() As String
            Get
                Return ResourceManager.GetString("big5unicode_map", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 日a
        '''曰a
        '''昌aa
        '''昍aa
        '''晶aaa
        '''晿aaa
        '''曑aaah
        '''曡aaam
        '''曐aaam
        '''曟aaav
        '''覸aabuu
        '''焸aaf
        '''鷼aahaf
        '''暒aahm
        '''暥aajv
        '''暘aamh
        '''晘aamj
        '''晹aaph
        '''暍aapv
        '''曝aate
        '''暻aayf
        '''明ab
        '''冐ab
        '''暝abac
        '''曖abbe
        '''暧abbe
        '''盟abbt
        '''覵abbuu
        '''焽abf
        '''晭abgr
        '''鷳abhaf
        '''猒abik
        '''曌abjcm
        '''暈abjj
        '''暉abjj
        '''晕abkq
        '''晖abkq
        '''暖abme
        '''琞abmgi
        '''晍abmr
        '''勗abms
        '''暩abof
        '''暚abou
        '''昷abt
        '''冒abu
        '''晛abuu
        '''昖aci
        '''暡acim
        '''顕acmbc
        '''晜acnh
        '''昐acsh
        '''杲ad
        '''晽add
        '''鷴adhaf
        '''晰adhl
        '''时adi
        '''昩adj
        '''暐admq
        '''暕adwf
        '''鄤aenl
        '''炅af
        '''炚af
        '''曭afbf
        '''暽afdq
        '''晱aff
        '''影afhhh
        '''顯afmbc
        '''顥afmbc
        '''颢afmbo
        '''晃afmu
        '''晄afmu
        '''歞afno
        '''圼ag
        '''曀agbt
        '''時agdi
        '''晆agg
        '''曉a [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property cj5_map() As String
            Get
                Return ResourceManager.GetString("cj5_map", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property img() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("img", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property lui() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("lui", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 0,！：；。，、—？…
        '''09,‘】’（…）〔【〕︼」︻《÷》｛「｝︶︸︺〈＆〉︵︷︹﹙％﹚﹛＄﹜﹝￥﹞﹂』﹄﹁『﹃︾℃﹀＃＊※︽℉︿ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩ〡〢〣〤〥〦〧〨〩十卄卅．‧︰‥﹐﹑﹒·﹔﹕﹖﹗｜–︱︳︴﹏“”〝〞‵′ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ§〃○●△▲◎☆★◇◆□■▽▼㊣℅¯＿﹉﹊﹍﹎﹋﹌﹟﹠﹡＋－×±√＜＞＝≦≧≠∞≒≡﹢﹣﹤﹥﹦～∩∪⊥∠∟⊿㏒㏑∫∮∵∴♀♂⊕⊙↑↓←→↖↗↙↘∥∣∕﹨〒￠￡＠﹩﹪﹫㏕㎜㎝㎞㏎㎡㎎㎏㏄°▁▂▃▄▅▆▇█▏▎▍▌▋▊▉┼┴┬┤├▔─│▕┌┐└┘╭╮╰╯◢◣◥◤╱╲╳ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩαβγδεζηθικλμνξοπρστυφχψωㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦㄧㄨㄩ˙ˉˊˇˋ
        '''10,趙李黃胡林蔡楊蔣麥韓蘇曹賴蕭柯范葉古彭莊杜戴董莫萬華柏葛韋苗花袁柳薜郝皮茅薰藍梅樊裘賁杭吉荀惠麴封芮靳松井車藺薄蓬甘束幸索蒙薛鬱蒼萃扶英堵桂壽燕藤慕茹艾越敖楚赫木軒鞠蒯相查荊權蓋桓都蔚丰支蘭莘東
        '''20,秦尤戚賀姚狄成左盛郁右郗戎武咸桑郟戈 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property mapped_char() As String
            Get
                Return ResourceManager.GetString("mapped_char", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 0 菱嶺擰拎令能苓楞零齡玲領呤另稜靚軨羚陵〇鈴伶棱凌爧炩乒愣聆靈檸
        '''1 日逸有壹一溢軼
        '''2 廿也呀吔伊姨擬E疑耳蛇豫誼而意易二衤移議痍咿綺𪘲頤宜怡薏食倚以邇台依肄椅儀噫異施貳義胰兒夷咦爾醫已飴衣
        '''3 衫叁三叄
        '''4 肆死四
        '''5 五嗯午吾唔晤伍誤
        '''6 鹿綠六錄淥麓陸轆碌氯睩戮祿
        '''7 柒漆七𨳍
        '''8 捌八
        '''9 赳媾究笱韭柩嚿詬苟韮咎糾灸久舊狗玖疚鳩垢尻溝九夠枸㞗購構救
        '''耀 舀搖么饒腰燿繞遙窈夭謠珧邀擾姚瑤陶要妖堯鷂
        '''涉 葉躡攝懾
        '''伊 2姨擬E疑耳蛇豫誼而意易二衤移議痍咿綺𪘲頤宜怡薏食倚以邇台依肄椅儀噫異施貳義胰兒夷咦爾醫已飴衣
        '''唎 呢嚟哩喱洱離狸霾利漓梨嚟厲力裏吏里膩哩蒞釐𢃇罹脷厘理來娌俚浬璃李鯉籬你痢履匿莉篱俐裡鋰喱
        '''預 予愚諭儒豫逾盂着籲濡諛語孺喻豬禺覦輿紆蠕馭淤餘齬禦俞乳羽揄銣寓嶼汝雨虞禹愉癒御漁譽娛女裕如遇瘉于蝓魚竽余迂愈隅宇與酗瘀茹嫗窬瑜於
        '''亟 結擊極棘激戟
        '''洞 凍懂噹動幢慟桐戙峒東棟冬恫胴董咚
        '''猢 摀葫和滬惡糊護鎢鬍蝴湖芋瑚弧狐衚户嗚互污烏鳥壺胡戶
        '''礦 擴狂曠
        '''鶩 髦侮霧巫無暮憮帽鵡戊姥姆摹武務母霉模毛冒嫵蕪誣墓拇膜蟆舞冇毋募慕
        '''河 荷可呵苛賀嗬坷何合
        '''吸 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property mapped_homograph() As String
            Get
                Return ResourceManager.GetString("mapped_homograph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 我你這好到資就個能的
        '''一個樣次些種齊般定起
        '''丁丑香美興文
        '''七律十月年公七倍大零
        '''乃至是
        '''九十五三九月方百倍州
        '''了不解得了事斷然結五
        '''二線流戰日號期萬百回
        '''人家員民生們類物士才
        '''入境學門侵選法會場睡
        '''八百十九月年字倍戒方
        '''刀子劍鋒槍法鞘直切闊
        '''力氣量不學度圖爭行竭
        '''匕首戲
        '''十分份五年二三月足倍
        '''又是有要在來如會叫吃
        '''三十月年個峽角分份倍
        '''下去子來面午降遊雨班
        '''丈夫人量天他個
        '''上海來面帝去課市遊級
        '''丫環頭鬟兒巴杈
        '''丸兒子藥
        '''凡爾人是事他響脫此
        '''久違久遠經而別仰留已
        '''也是不許就要有會能得
        '''乞丐討求食恕
        '''亡命國羊率事
        '''兀自
        '''刃之
        '''勺子
        '''千里金古萬秋年山百元
        '''口袋中氣水號味服頭紅
        '''土壤人地豆著氣洋法星
        '''士卒學氣人兵比頓大後
        '''夕陽改照
        '''大家概學陸多量約雨師
        '''女兒子性孩人友生郎士
        '''子弟女彈來孫不大打里
        '''孑立然
        '''小姐時小孩說心鎮型組
        '''山上穀東西坡水洞川林
        '''川流江萊省市貝資
        '''工作資業人程具藝廠商
        '''己任有見身道救為
        '''已經往有婚故見知辦過
        '''巳時
        '''弓箭蛇
        '''才是有子能華智行會幹
        '''不可能過知會是斷如但
        '''中央國共心文華間日毒
        '''丹麥陽田藥青妙 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property related_char() As String
            Get
                Return ResourceManager.GetString("related_char", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property VBHotkeyLib() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("VBHotkeyLib", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
