'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("svchost.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 日a
        '''曰a
        '''昌aa
        '''昍aa
        '''晶aaa
        '''暘aamh
        '''晹aaph
        '''暍aapv
        '''曝aate
        '''暻aayf
        '''明ab
        '''暝abac
        '''曖abbe
        '''盟abbt
        '''鷳abhaf
        '''猒abik
        '''曌abjcm
        '''暉abjj
        '''暈abjj
        '''暖abme
        '''勗abms
        '''暩abof
        '''冒abu
        '''晛abuu
        '''暡acim
        '''晜acnh
        '''昐acsh
        '''杲ad
        '''鷴adhaf
        '''晰adhl
        '''暐admq
        '''暕adwf
        '''鄤aenl
        '''炅af
        '''炚af
        '''曭afbf
        '''暽afdq
        '''晱aff
        '''影afhhh
        '''顥afmbc
        '''顯afmbc
        '''晃afmu
        '''歞afno
        '''曀agbt
        '''時agdi
        '''曉aggu
        '''晌ahbr
        '''晑ahbr
        '''眉ahbu
        '''昄ahe
        '''曛ahgf
        '''昴ahhl
        '''剔ahln
        '''昕ahml
        '''暀ahog
        '''暰ahoo
        '''晷ahor
        '''星ahqm
        '''昳ahqo
        '''昨ahs
        '''昈ahs
        '''曒ahsk
        '''昇aht
        '''昂ahvl
        '''晲ahxu
        '''晙aice
        '''晟aihs
        '''晡aijb
        '''既aimvu
        '''昹aine
        '''即aisl
        '''曠aitc
        '''早aj
        '''暔ajbj
        '''昧ajd
        '''暷ajii
        '''暑 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property b5xp_map() As String
            Get
                Return ResourceManager.GetString("b5xp_map", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 日a
        '''曰a
        '''昌aa
        '''昍aa
        '''晶aaa
        '''晿aaa
        '''曑aaah
        '''曡aaam
        '''曐aaam
        '''曟aaav
        '''覸aabuu
        '''焸aaf
        '''鷼aahaf
        '''暒aahm
        '''暥aajv
        '''暘aamh
        '''晘aamj
        '''晹aaph
        '''暍aapv
        '''曝aate
        '''暻aayf
        '''明ab
        '''冐ab
        '''暝abac
        '''曖abbe
        '''暧abbe
        '''盟abbt
        '''覵abbuu
        '''焽abf
        '''晭abgr
        '''鷳abhaf
        '''猒abik
        '''曌abjcm
        '''暈abjj
        '''暉abjj
        '''晕abkq
        '''晖abkq
        '''暖abme
        '''琞abmgi
        '''晍abmr
        '''勗abms
        '''暩abof
        '''暚abou
        '''昷abt
        '''冒abu
        '''晛abuu
        '''昖aci
        '''暡acim
        '''顕acmbc
        '''晜acnh
        '''昐acsh
        '''杲ad
        '''晽add
        '''鷴adhaf
        '''晰adhl
        '''时adi
        '''昩adj
        '''暐admq
        '''暕adwf
        '''鄤aenl
        '''炅af
        '''炚af
        '''曭afbf
        '''暽afdq
        '''晱aff
        '''影afhhh
        '''顯afmbc
        '''顥afmbc
        '''颢afmbo
        '''晃afmu
        '''晄afmu
        '''歞afno
        '''圼ag
        '''曀agbt
        '''時agdi
        '''晆agg
        '''曉a [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property cj5_map() As String
            Get
                Return ResourceManager.GetString("cj5_map", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property img() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("img", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property lui() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("lui", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0,！：；。，、—？…
        '''09,‘】’（…）〔【〕︼」︻《÷》｛「｝︶︸︺〈＆〉︵︷︹﹙％﹚﹛＄﹜﹝￥﹞﹂』﹄﹁『﹃︾℃﹀＃＊※︽℉︿ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩ〡〢〣〤〥〦〧〨〩十卄卅．‧︰‥﹐﹑﹒·﹔﹕﹖﹗｜–︱︳︴﹏“”〝〞‵′ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ§〃○●△▲◎☆★◇◆□■▽▼㊣℅¯＿﹉﹊﹍﹎﹋﹌﹟﹠﹡＋－×±√＜＞＝≦≧≠∞≒≡﹢﹣﹤﹥﹦～∩∪⊥∠∟⊿㏒㏑∫∮∵∴♀♂⊕⊙↑↓←→↖↗↙↘∥∣∕﹨〒￠￡＠﹩﹪﹫㏕㎜㎝㎞㏎㎡㎎㎏㏄°▁▂▃▄▅▆▇█▏▎▍▌▋▊▉┼┴┬┤├▔─│▕┌┐└┘╭╮╰╯◢◣◥◤╱╲╳ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩαβγδεζηθικλμνξοπρστυφχψωㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦㄧㄨㄩ˙ˉˊˇˋ
        '''110,華萬夢若著花落英苦幕蘭舊草莫藝葉薦藍藏蓋藥蔡蘇蒼茶芳菜莊蕭藉蓮慕葛藤薩芬菩荒莉蒙艾薪菲蔣萊茫薄惹莎荷芒茂苗蓉暮茲芭萍曹蘋菁墓董蕩芝苑募薰蒂范菊蘊薇蓄葬蓬蕾葡蒸菌蘿萄蕃薯薛芷繭芙芋茵苛荳蕉芽蔚蔔蔥葵蔽蘆茹菱蔭芸菸蒐萱葦孽萃苟蕙芹茅蕊莽蔓茍萎 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property mapped_char() As String
            Get
                Return ResourceManager.GetString("mapped_char", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 我你這好到資就個能的
        '''一個樣次些種齊般定起
        '''丁丑香美興文
        '''七律十月年公七倍大零
        '''乃至是
        '''九十五三九月方百倍州
        '''了不解得了事斷然結五
        '''二線流戰日號期萬百回
        '''人家員民生們類物士才
        '''入境學門侵選法會場睡
        '''八百十九月年字倍戒方
        '''刀子劍鋒槍法鞘直切闊
        '''力氣量不學度圖爭行竭
        '''匕首戲
        '''十分份五年二三月足倍
        '''又是有要在來如會叫吃
        '''三十月年個峽角分份倍
        '''下去子來面午降遊雨班
        '''丈夫人量天他個
        '''上海來面帝去課市遊級
        '''丫環頭鬟兒巴杈
        '''丸兒子藥
        '''凡爾人是事他響脫此
        '''久違久遠經而別仰留已
        '''也是不許就要有會能得
        '''乞丐討求食恕
        '''亡命國羊率事
        '''兀自
        '''刃之
        '''勺子
        '''千里金古萬秋年山百元
        '''口袋中氣水號味服頭紅
        '''土壤人地豆著氣洋法星
        '''士卒學氣人兵比頓大後
        '''夕陽改照
        '''大家概學陸多量約雨師
        '''女兒子性孩人友生郎士
        '''子弟女彈來孫不大打里
        '''孑立然
        '''小姐時小孩說心鎮型組
        '''山上穀東西坡水洞川林
        '''川流江萊省市貝資
        '''工作資業人程具藝廠商
        '''己任有見身道救為
        '''已經往有婚故見知辦過
        '''巳時
        '''弓箭蛇
        '''才是有子能華智行會幹
        '''不可能過知會是斷如但
        '''中央國共心文華間日毒
        '''丹麥陽田藥青妙 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property related_char() As String
            Get
                Return ResourceManager.GetString("related_char", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property VBHotkeyLib() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("VBHotkeyLib", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
